create or replace sequence dng_contract_id;

CREATE TABLE star.contracts(acceptor_id BIGINT,
assignee_id BIGINT,
availability VARCHAR,
collateral DOUBLE,
contract_id BIGINT,
date_accepted TIMESTAMP,
date_completed TIMESTAMP,
date_expired TIMESTAMP,
date_issued TIMESTAMP,
days_to_complete BIGINT,
end_location_id BIGINT,
for_corporation BOOLEAN,
issuer_corporation_id BIGINT,
issuer_id BIGINT,
price DOUBLE,
reward DOUBLE,
start_location_id BIGINT,
status VARCHAR,
title VARCHAR,
"type" VARCHAR,
volume DOUBLE,
import_id INTEGER,
record_id BIGINT,
contract_key BIGINT default nextval('dng_contract_id'),
dw_valid_from TIMESTAMP,
dw_valid_to TIMESTAMP,
dw_is_current VARCHAR(10)
);
