INSERT INTO star.contracts (
  acceptor_id ,
  assignee_id ,
  availability ,
  collateral ,
  contract_id ,
  date_accepted ,
  date_completed ,
  date_expired ,
  date_issued ,
  days_to_complete ,
  end_location_id ,
  for_corporation ,
  issuer_corporation_id ,
  issuer_id ,
  price ,
  reward ,
  start_location_id ,
  status ,
  title ,
  type,
  volume,
)
SELECT 
acceptor_id ,
assignee_id ,
availability ,
collateral ,
contract_id ,
date_accepted ,
date_completed ,
date_expired ,
date_issued ,
days_to_complete ,
end_location_id ,
for_corporation ,
issuer_corporation_id ,
issuer_id ,
price ,
reward ,
start_location_id ,
status ,
title ,
"type",
volume,
FROM stg.dng_contract as source


